In [1]:
import pandas as pd

In [ ]:
# list of the teams (18/19)
# data from three different sources use different names for teams. 
# manually making a dictionary to rename teams
team_dict = {
            'Arsenal FC': 'Arsenal',
            'Burnley FC': 'Burnley',
            'Liverpool FC': 'Liverpool',
            'Everton FC': 'Everton',
            'Fulham FC': 'Fulham',
            'Southampton FC': 'Southampton',
            'Chelsea FC': 'Chelsea',
            'West Bromwich Albion': 'West Bromwich',
            'Manchester United': 'Manchester Utd',
            'Man United': 'Manchester Utd',
            'Man City': 'Manchester City', 
            'Newcastle': 'Newcastle Utd',
            'Newcastle United': 'Newcastle Utd',
            'West Ham United': 'West Ham Utd', 
            'Tottenham Hotspur': 'Tottenham',
            'Queens Park Rangers': 'QP Rangers',
            'Watford FC': 'Watford',
            'AFC Bournemouth': 'Bournemouth',
            'Sunderland AFC': 'Sunderland',
            'Middlesbrough FC': 'Middlesbrough',
            'Brighton & Hove Albion': 'Brighton & Hove',
            'Huddersfield Town': 'Huddersfield',
            'QPR': 'QP Rangers',
            'Cardiff': 'Cardiff City',
            'Hull': 'Hull City',
            'Norwich': 'Norwich City',
            'Stoke': 'Stoke City',
            'Swansea': 'Swansea City',
            'West Brom': 'West Bromwich',
            'West Ham': 'West Ham Utd'
            }

In [2]:
# Current season Roster Power Index(RPI) from PES Database.
# Each data is used to predict each season.
# For example, use pes14 to predict (train) 14/15 season.
# Merge pes14 data with epl_table_1314 table in order to predict EPL 14/15 season.
pes14 = pd.read_csv('./Data/PES14.csv')
pes15 = pd.read_csv('./Data/PES15.csv')
pes16 = pd.read_csv('./Data/PES16.csv')
pes17 = pd.read_csv('./Data/PES17.csv')
pes18 = pd.read_csv('./Data/PES18.csv')
pes19 = pd.read_csv('./Data/PES19.csv')

In [3]:
pes15

               Team  Ovr  Def  Mid  Fwd  Phy  Spd
0   Manchester City   81   81   83   82   82   76
1           Chelsea   79   77   82   82   80   77
2         Liverpool   79   78   81   80   79   79
3    Manchester Utd   78   74   79   83   77   78
4         Tottenham   77   78   75   78   79   77
5           Arsenal   77   77   76   81   77   75
6     Newcastle Utd   75   76   77   73   78   76
7     West Bromwich   75   74   76   71   80   73
8         Hull City   75   75   76   77   78   75
9           Everton   74   72   75   76   76   75
10       QP Rangers   74   73   75   75   77   74
11       Stoke City   74   72   74   78   79   71
12       Sunderland   74   76   75   71   78   73
13      Aston Villa   74   74   75   77   79   76
14     West Ham Utd   73   72   73   73   79   73
15      Southampton   73   74   73   74   77   75
16   Crystal Palace   73   75   72   73   79   74
17     Swansea City   72   71   73   75   76   73
18   Leicester City   69   70   71   66   73   72
19          Burnley   68   66   68   69   73   70

In [4]:
# Past season RPI from past season.
epl_table_1314 = pd.read_csv('./Data/epl_table_1314.csv')
epl_table_1415 = pd.read_csv('./Data/epl_table_1415.csv')
epl_table_1516 = pd.read_csv('./Data/epl_table_1516.csv')
epl_table_1617 = pd.read_csv('./Data/epl_table_1617.csv')
epl_table_1718 = pd.read_csv('./Data/epl_table_1718.csv')

In [5]:
epl_table_1415.sort_values(by='PTS', ascending=False)

,Team,P,W,D,L,GF,GA,HW,HGF,HGA,...,AGA,PTS,H_Att,A_Att,H_Def,A_Def,YC,RC,DIS,CS
3,Chelsea,38,26,9,3,73,32,15,36,9,...,23,87,1.285714,1.783133,0.433735,0.821429,72,4,1.157895,17
9,Manchester City,38,24,7,7,83,38,14,44,14,...,24,79,1.571429,1.879518,0.674699,0.857143,75,2,1.092105,14
0,Arsenal,38,22,9,7,71,36,12,41,14,...,22,75,1.464286,1.445783,0.674699,0.785714,67,2,0.986842,13
10,Manchester Utd,38,20,10,8,62,37,14,41,15,...,22,70,1.464286,1.012048,0.722892,0.785714,62,5,1.078947,11
17,Tottenham,38,19,7,12,58,53,10,31,24,...,29,64,1.107143,1.301205,1.156627,1.035714,78,4,1.236842,9
8,Liverpool,38,18,8,12,52,48,10,30,20,...,28,62,1.071429,1.060241,0.963855,1.000000,64,3,1.000000,14
13,Southampton,38,18,6,14,54,33,11,37,13,...,20,60,1.321429,0.819277,0.626506,0.714286,56,3,0.894737,15
16,Swansea City,38,16,8,14,46,49,9,27,22,...,27,56,0.964286,0.915663,1.060241,0.964286,45,5,0.855263,13
14,Stoke City,38,15,9,14,48,45,10,32,22,...,23,54,1.142857,0.771084,1.060241,0.821429,79,1,1.092105,9
4,Crystal Palace,38,13,9,16,47,51,6,21,27,...,24,48,0.750000,1.253012,1.301205,0.857143,59,4,0.986842,7
5,Everton,38,12,11,15,48,50,7,27,21,...,29,47,0.964286,1.012048,1.012048,1.035714,64,2,0.947368,10
19,West Ham Utd,38,12,11,15,44,47,9,25,18,...,29,47,0.892857,0.915663,0.867470,1.035714,64,2,0.947368,9
18,West Bromwich,38,11,11,16,38,51,7,24,26,...,25,44,0.857143,0.674699,1.253012,0.892857,64,3,1.000000,16
7,Leicester City,38,11,8,19,46,55,7,28,22,...,33,41,1.000000,0.867470,1.060241,1.178571,49,4,0.855263,10
11,Newcastle Utd,38,10,9,19,40,63,7,26,27,...,36,39,0.928571,0.674699,1.301205,1.285714,59,7,1.144737,8
1,Aston Villa,38,10,8,20,31,57,5,18,25,...,32,38,0.642857,0.626506,1.204819,1.142857,66,7,1.236842,10
15,Sunderland,38,7,17,14,31,53,4,16,27,...,26,38,0.571429,0.722892,1.301205,0.928571,94,2,1.342105,13
6,Hull City,38,8,11,19,33,51,5,19,24,...,27,35,0.678571,0.674699,1.156627,0.964286,72,6,1.263158,10
2,Burnley,38,7,12,19,28,53,4,14,21,...,32,33,0.500000,0.674699,1.012048,1.142857,63,2,0.934211,10
12,QP Rangers,38,8,6,24,42,73,6,23,24,...,49,30,0.821429,0.915663,1.156627,1.750000,73,3,1.118421,6

In [6]:
pr_14 = pd.merge(pes14, epl_table_1314, on='Team', how='outer').sort_values(by='Team')
pr_15 = pd.merge(pes15, epl_table_1415, on='Team', how='outer').sort_values(by='Team')
pr_16 = pd.merge(pes16, epl_table_1516, on='Team', how='outer').sort_values(by='Team')
pr_17 = pd.merge(pes17, epl_table_1617, on='Team', how='outer').sort_values(by='Team')
pr_18 = pd.merge(pes18, epl_table_1718, on='Team', how='outer').sort_values(by='Team')

In [7]:
pr_18.sort_values(by='PTS', ascending=False)

,Team,Ovr,Def,Mid,Fwd,Phy,Spd,P,W,D,...,AGA,PTS,H_Att,A_Att,H_Def,A_Def,YC,RC,DIS,CS
1,Manchester City,83,82,83,85,75,79,38,32,4,...,13,100,2.096220,2.064220,0.642202,0.446735,57,2,0.855263,18
2,Manchester Utd,83,81,84,85,79,77,38,25,6,...,19,81,1.305842,1.376147,0.412844,0.652921,64,1,0.894737,19
4,Tottenham,82,81,82,82,78,77,38,23,8,...,20,77,1.374570,1.559633,0.733945,0.687285,49,2,0.750000,16
5,Liverpool,80,80,82,82,74,79,38,21,12,...,28,75,1.546392,1.788991,0.458716,0.962199,44,1,0.631579,17
0,Chelsea,83,82,82,85,77,79,38,21,7,...,22,70,1.030928,1.467890,0.733945,0.756014,40,4,0.736842,16
3,Arsenal,82,81,82,84,75,76,38,19,6,...,31,63,1.855670,0.917431,0.917431,1.065292,57,2,0.855263,13
17,Burnley,75,75,76,75,75,73,38,14,12,...,22,54,0.549828,0.917431,0.779817,0.756014,65,0,0.855263,12
6,Everton,80,81,81,79,80,75,38,13,10,...,36,49,0.962199,0.733945,1.009174,1.237113,49,3,0.802632,10
8,Leicester City,78,77,78,77,77,74,38,12,11,...,38,47,0.859107,1.422018,1.009174,1.305842,48,5,0.894737,9
9,Crystal Palace,78,77,78,80,78,75,38,11,11,...,28,44,0.996564,0.733945,1.238532,0.962199,72,0,0.947368,9
15,Bournemouth,76,75,76,76,74,78,38,11,11,...,31,44,0.893471,0.871560,1.376147,1.065292,54,1,0.763158,6
18,Newcastle Utd,75,75,75,76,76,76,38,12,8,...,30,44,0.721649,0.825688,0.779817,1.030928,51,2,0.776316,9
7,West Ham Utd,78,78,79,77,77,75,38,10,12,...,42,42,0.824742,1.100917,1.192661,1.443299,72,2,1.052632,10
11,Watford,77,76,77,78,78,74,38,11,8,...,33,41,0.927835,0.779817,1.422018,1.134021,62,4,1.026316,9
16,Brighton & Hove,75,74,76,76,76,74,38,9,13,...,29,40,0.824742,0.458716,1.146789,0.996564,54,2,0.815789,10
19,Huddersfield,74,74,73,74,74,76,38,9,10,...,33,37,0.549828,0.550459,1.146789,1.134021,59,3,0.934211,10
10,Southampton,77,78,77,78,75,75,38,7,15,...,30,36,0.687285,0.779817,1.192661,1.030928,62,2,0.921053,8
12,Stoke City,77,77,78,76,76,74,38,7,12,...,38,33,0.687285,0.688073,1.376147,1.305842,62,1,0.868421,6
13,Swansea City,77,76,77,77,77,76,38,8,9,...,32,33,0.584192,0.504587,1.100917,1.099656,51,1,0.723684,9
14,West Bromwich,77,77,77,79,77,73,38,6,13,...,27,31,0.721649,0.458716,1.330275,0.927835,73,1,1.013158,10

In [8]:
epl_detail_1314 = pd.read_csv('./Data/epl1314.csv')

In [9]:
epl_detail_1314 = epl_detail_1314[['HomeTeam', 'AwayTeam', 'FTR']]

In [11]:
new_cols = ['HtOff', 'HtDef', 'AtOff', 'AtDef']
epl_detail_1314 = epl_detail_1314.reindex(columns=epl_detail_1314.columns.tolist() + new_cols)
#epl_detail_1314[new_cols] = new_vals

In [13]:
epl_detail_1314 = epl_detail_1314.replace(team_dict)

In [14]:
for team in epl_detail_1314['HomeTeam']:
    ht_off = pr_14.loc[pr_14['Team'] == team, 'H_Att'].values[0] 
    ht_def = pr_14.loc[pr_14['Team'] == team, 'H_Def'].values[0]
    at_off = pr_14.loc[pr_14['Team'] == team, 'A_Att'].values[0]
    at_def = pr_14.loc[pr_14['Team'] == team, 'H_Def'].values[0]
    
    epl_detail_1314.loc[epl_detail_1314['HomeTeam'] == team, 'HtOff'] = ht_off
    epl_detail_1314.loc[epl_detail_1314['HomeTeam'] == team, 'HtDef'] = ht_def
    epl_detail_1314.loc[epl_detail_1314['AwayTeam'] == team, 'AtOff'] = at_off
    epl_detail_1314.loc[epl_detail_1314['AwayTeam'] == team, 'AtDef'] = at_def

In [15]:
epl_detail_1314

,HomeTeam,AwayTeam,FTR,HtOff,HtDef,AtOff,AtDef
0,Arsenal,Aston Villa,A,1.204013,0.484581,0.748899,1.277533
1,Liverpool,Stoke City,H,1.772575,0.792952,0.792952,0.748899
2,Norwich City,Everton,D,0.568562,0.792952,1.013216,0.837004
3,Sunderland,Fulham,A,0.702341,1.189427,0.704846,1.674009
4,Swansea City,Manchester Utd,A,1.103679,1.145374,1.541850,0.925110
5,West Bromwich,Southampton,A,0.802676,1.189427,0.969163,1.013216
6,West Ham Utd,Cardiff City,H,0.836120,1.145374,0.528634,1.541850
7,Chelsea,Hull City,H,1.438127,0.484581,0.792952,0.925110
8,Crystal Palace,Tottenham,A,0.602007,1.013216,1.101322,1.013216
9,Manchester City,Newcastle Utd,H,2.107023,0.572687,0.881057,1.233480
10,Chelsea,Aston Villa,H,1.438127,0.484581,0.748899,1.277533
11,Aston Villa,Liverpool,A,0.735786,1.277533,2.114537,0.792952
12,Everton,West Bromwich,D,1.270903,0.837004,0.837004,1.189427
13,Fulham,Arsenal,A,0.802676,1.674009,1.409692,0.484581
14,Hull City,Norwich City,H,0.668896,0.925110,0.484581,0.792952
15,Newcastle Utd,West Ham Utd,D,0.769231,1.233480,0.660793,1.145374
16,Southampton,Sunderland,D,1.070234,1.013216,0.881057,1.189427
17,Stoke City,Crystal Palace,H,0.903010,0.748899,0.660793,1.013216
18,Cardiff City,Manchester City,H,0.668896,1.541850,1.718062,0.572687
19,Tottenham,Swansea City,H,1.003344,1.013216,0.925110,1.145374
20,Manchester Utd,Chelsea,D,0.969900,0.925110,1.233480,0.484581
21,Cardiff City,Everton,D,0.668896,1.541850,1.013216,0.837004
22,Crystal Palace,Sunderland,H,0.602007,1.013216,0.881057,1.189427
23,Manchester City,Hull City,H,2.107023,0.572687,0.792952,0.925110
24,Newcastle Utd,Fulham,H,0.769231,1.233480,0.704846,1.674009
25,Norwich City,Southampton,H,0.568562,0.792952,0.969163,1.013216
26,West Ham Utd,Stoke City,A,0.836120,1.145374,0.792952,0.748899
27,Arsenal,Tottenham,H,1.204013,0.484581,1.101322,1.013216
28,Liverpool,Manchester Utd,H,1.772575,0.792952,1.541850,0.925110
29,West Bromwich,Swansea City,A,0.802676,1.189427,0.925110,1.145374
...,...,...,...,...,...,...,...
350,Stoke City,Tottenham,A,0.903010,0.748899,1.101322,1.013216
351,Swansea City,Aston Villa,H,1.103679,1.145374,0.748899,1.277533
352,West Bromwich,West Ham Utd,H,0.802676,1.189427,0.660793,1.145374
353,Crystal Palace,Manchester City,A,0.602007,1.013216,1.718062,0.572687
354,Liverpool,Chelsea,A,1.772575,0.792952,1.233480,0.484581
355,Sunderland,Cardiff City,H,0.702341,1.189427,0.528634,1.541850
356,Arsenal,Newcastle Utd,H,1.204013,0.484581,0.881057,1.233480
357,Aston Villa,Hull City,H,0.735786,1.277533,0.792952,0.925110
358,Everton,Manchester City,A,1.270903,0.837004,1.718062,0.572687
359,Manchester Utd,Sunderland,A,0.969900,0.925110,0.881057,1.189427
360,Newcastle Utd,Cardiff City,H,0.769231,1.233480,0.528634,1.541850
361,Stoke City,Fulham,H,0.903010,0.748899,0.704846,1.674009
362,Swansea City,Southampton,A,1.103679,1.145374,0.969163,1.013216
363,West Ham Utd,Tottenham,H,0.836120,1.145374,1.101322,1.013216
364,Arsenal,West Bromwich,H,1.204013,0.484581,0.837004,1.189427
365,Chelsea,Norwich City,D,1.438127,0.484581,0.484581,0.792952
366,Crystal Palace,Liverpool,D,0.602007,1.013216,2.114537,0.792952
367,Manchester Utd,Hull City,H,0.969900,0.925110,0.792952,0.925110
368,Manchester City,Aston Villa,H,2.107023,0.572687,0.748899,1.277533
369,Sunderland,West Bromwich,H,0.702341,1.189427,0.837004,1.189427
370,Cardiff City,Chelsea,A,0.668896,1.541850,1.233480,0.484581
371,Fulham,Crystal Palace,D,0.802676,1.674009,0.660793,1.013216
372,Hull City,Everton,A,0.668896,0.925110,1.013216,0.837004
373,Liverpool,Newcastle Utd,H,1.772575,0.792952,0.881057,1.233480
374,Manchester City,West Ham Utd,H,2.107023,0.572687,0.660793,1.145374
375,Norwich City,Arsenal,A,0.568562,0.792952,1.409692,0.484581
376,Southampton,Manchester Utd,D,1.070234,1.013216,1.541850,0.925110
377,Sunderland,Swansea City,A,0.702341,1.189427,0.925110,1.145374
378,Tottenham,Aston Villa,H,1.003344,1.013216,0.748899,1.277533
379,West Bromwich,Stoke City,A,0.802676,1.189427,0.792952,0.748899

In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [17]:
lr = LogisticRegression()

In [20]:
X = epl_detail_1314[['HtOff', 'HtDef', 'AtOff', 'AtDef']]
y = epl_detail_1314['FTR']

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, stratify=y, test_size = .33)

In [28]:
lr.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [29]:
lr.predict(X_test)

array(['A', 'H', 'H', 'H', 'H', 'A', 'H', 'A', 'H', 'H', 'H', 'H', 'A',
       'A', 'A', 'H', 'A', 'H', 'H', 'A', 'H', 'H', 'A', 'H', 'H', 'H',
       'H', 'H', 'H', 'H', 'H', 'A', 'A', 'A', 'H', 'H', 'A', 'H', 'H',
       'H', 'H', 'A', 'H', 'A', 'H', 'H', 'H', 'A', 'A', 'H', 'H', 'A',
       'A', 'A', 'H', 'H', 'H', 'H', 'A', 'A', 'H', 'H', 'A', 'A', 'A',
       'A', 'A', 'H', 'H', 'H', 'H', 'H', 'A', 'A', 'A', 'H', 'H', 'H',
       'H', 'H', 'H', 'H', 'A', 'H', 'H', 'A', 'A', 'H', 'H', 'A', 'H',
       'A', 'H', 'H', 'A', 'A', 'H', 'H', 'H', 'H', 'H', 'A', 'H', 'A',
       'A', 'A', 'H', 'A', 'A', 'H', 'H', 'A', 'A', 'A', 'H', 'H', 'A',
       'H', 'A', 'H', 'H', 'H', 'A', 'H', 'H', 'A'], dtype=object)

In [39]:
lr.score(X_train, y_train)

0.6023622047244095

In [41]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [44]:
rf.score(X_train, y_train)

0.9606299212598425

In [45]:
rf.predict(X_test)

array(['A', 'H', 'H', 'D', 'H', 'H', 'H', 'A', 'H', 'A', 'D', 'A', 'A',
       'A', 'A', 'H', 'A', 'H', 'D', 'A', 'A', 'H', 'A', 'H', 'H', 'H',
       'H', 'A', 'H', 'H', 'H', 'H', 'A', 'A', 'H', 'H', 'A', 'H', 'H',
       'H', 'H', 'H', 'H', 'D', 'H', 'A', 'A', 'D', 'A', 'D', 'A', 'A',
       'A', 'A', 'A', 'H', 'H', 'H', 'H', 'A', 'D', 'H', 'A', 'A', 'A',
       'A', 'H', 'D', 'H', 'H', 'H', 'H', 'H', 'A', 'A', 'H', 'H', 'D',
       'H', 'A', 'H', 'A', 'H', 'D', 'H', 'A', 'A', 'A', 'H', 'A', 'H',
       'A', 'H', 'H', 'A', 'A', 'H', 'A', 'A', 'A', 'D', 'H', 'H', 'A',
       'H', 'A', 'H', 'A', 'D', 'A', 'H', 'A', 'D', 'A', 'H', 'H', 'D',
       'A', 'A', 'H', 'H', 'D', 'A', 'H', 'A', 'A'], dtype=object)