In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import poisson

In [2]:
# list of the teams (18/19)
# data from three different sources use different names for teams. 
# manually making a dictionary to rename teams
team_name = {
            'Arsenal FC': 'Arsenal',
            'Burnley FC': 'Burnley',
            'Liverpool FC': 'Liverpool',
            'Everton FC': 'Everton',
            'Fulham FC': 'Fulham',
            'Southampton FC': 'Southampton',
            'Chelsea FC': 'Chelsea',
            'West Bromwich Albion': 'West Bromwich',
            'Manchester United': 'Manchester Utd',
            'Man United': 'Manchester Utd',
            'Man City': 'Manchester City', 
            'Newcastle': 'Newcastle Utd',
            'Newcastle United': 'Newcastle Utd',
            'West Ham United': 'West Ham Utd', 
            'Tottenham Hotspur': 'Tottenham',
            'Queens Park Rangers': 'QP Rangers',
            'Watford FC': 'Watford',
            'AFC Bournemouth': 'Bournemouth',
            'Sunderland AFC': 'Sunderland',
            'Middlesbrough FC': 'Middlesbrough',
            'Brighton & Hove Albion': 'Brighton & Hove',
            'Brighton': 'Brighton & Hove',
            'Huddersfield Town': 'Huddersfield',
            'QPR': 'QP Rangers',
            'Cardiff': 'Cardiff City',
            'Hull': 'Hull City',
            'Norwich': 'Norwich City',
            'Stoke': 'Stoke City',
            'Swansea': 'Swansea City',
            'West Brom': 'West Bromwich',
            'West Ham': 'West Ham Utd',
            'Reading FC': 'Reading',
            'Leicester': 'Leicester City'
            }

In [116]:
table_13 = pd.read_csv('./Data/epl_table_1314.csv')
table_14 = pd.read_csv('./Data/epl_table_1415.csv')
table_15 = pd.read_csv('./Data/epl_table_1516.csv')
table_16 = pd.read_csv('./Data/epl_table_1617.csv')
table_17 = pd.read_csv('./Data/epl_table_1718.csv')

table = [table_13, table_14, table_15, table_16, table_17]

In [222]:
# Season fixture
epl_detail_1314 = pd.read_csv('./Data/epl1314.csv').replace(team_name)[['HomeTeam', 'AwayTeam', 'FTR']]
epl_detail_1415 = pd.read_csv('./Data/epl1415.csv').replace(team_name)[['HomeTeam', 'AwayTeam', 'FTR']]
epl_detail_1516 = pd.read_csv('./Data/epl1516.csv').replace(team_name)[['HomeTeam', 'AwayTeam', 'FTR']]
epl_detail_1617 = pd.read_csv('./Data/epl1617.csv').replace(team_name)[['HomeTeam', 'AwayTeam', 'FTR']]
epl_detail_1718 = pd.read_csv('./Data/epl1718.csv').replace(team_name)[['HomeTeam', 'AwayTeam', 'FTR']]
epl_detail_1819 = pd.read_csv('./Data/epl1819.csv').replace(team_name)[['HomeTeam', 'AwayTeam', 'FTR']]

fixture = [epl_detail_1415, epl_detail_1516, epl_detail_1617, epl_detail_1718, epl_detail_1819]

In [223]:
'Arsenal' in list(table_13['Team'])

True

In [144]:
set(list(epl_detail_1819['HomeTeam']))

{'Arsenal',
 'Bournemouth',
 'Brighton & Hove',
 'Burnley',
 'Cardiff City',
 'Chelsea',
 'Crystal Palace',
 'Everton',
 'Fulham',
 'Huddersfield',
 'Leicester City',
 'Liverpool',
 'Manchester City',
 'Manchester Utd',
 'Newcastle Utd',
 'Southampton',
 'Tottenham',
 'Watford',
 'West Ham Utd',
 'Wolves'}

In [145]:
epl_detail_1314.head(2)

    HomeTeam     AwayTeam FTR
0    Arsenal  Aston Villa   A
1  Liverpool   Stoke City   H

In [146]:
table_13[['Team','H_Att', 'H_Def', 'A_Att', 'A_Def', 'HGF', 'HGA', 'AGA', 'AGF']].head(2)

          Team     H_Att     H_Def     A_Att     A_Def  HGF  HGA  AGA  AGF
0      Arsenal  1.204013  0.484581  1.409692  1.003344   36   11   30   32
1  Aston Villa  0.735786  1.277533  0.748899  1.070234   22   29   32   17

In [147]:
def result_percentage(dataframe, hometeam, awayteam):
    home_avg = dataframe['HGF'].sum()/380
    away_avg = dataframe['HGA'].sum()/380
    
    home_score = float(dataframe[dataframe['Team'] == hometeam]['H_Att']) * float(dataframe[dataframe['Team'] == awayteam]['A_Def']) * home_avg
    away_score = float(dataframe[dataframe['Team'] == awayteam]['A_Att']) * float(dataframe[dataframe['Team'] == hometeam]['H_Def']) * away_avg

    score = []
    # maximum score for a team is 5
    for goals in range(0, 6):
        scores = {}
        scores['Home'] = (poisson.pmf(goals, home_score) * 100) # Hometeam score
        scores['Away'] = (poisson.pmf(goals, away_score) * 100) # away score

        if len(scores) == 2:
                    score.append(scores)

    score = pd.DataFrame(score, columns=(['Home', 'Away']))
    # print(score)
    # % of home team winning
    # home score > away score
    # home[1] * away[0]
    # home[2] * away[0] + home[2] * away[1]
    # home[3] * away[0] + home[3] * away[1] + home[3] * away[2]
    # home[4] * away[0] + home[4] * away[1] + home[4] * away[2] + home[4] * away[3]
    # home[5] * away[0] + home[5] * away[1] + home[5] * away[2] + home[5] * away[3]+  home[5] * away[4]
    home_w = 0
    away_w = 0
    draw = 0
    result = []
    for home in range(1, len(score)):
        for away in range(0, home):
            home_w += (score['Home'][home] * score['Away'][away] / 10000)
    result.append(home_w)

    for away in range(1, len(score)):
        for home in range(0, away):
            away_w += (score['Home'][home] * score['Away'][away] / 10000)
    result.append(away_w)

    for home in range(0, len(score)):
        away = home
        draw += (score['Home'][home] * score['Away'][away] / 10000)
    result.append(draw)

    return result

In [148]:
result_percentage(table_13, 'Arsenal', 'Aston Villa')

[0.735833196878577, 0.06805488325845031, 0.1785172674952371]

In [250]:
def decision(result_p):
#     if result_p[2] >= 0.4:
#         return 'D'
#     elif abs(result_p[0] - result_p[1]) < 0.005:
#         return 'D'
    if result_p[2] > result_p[1] and result_p[2] > result_p[0]:
        return 'D'
    elif result_p[0] > result_p[1] and result_p[0] > result_p[2]:
        return 'H'
    elif result_p[1] > result_p[0] and result_p[1] > result_p[2]:
        return 'A'

In [251]:
def predict(fixture, rating):

    for i in range(len(fixture)):
        if fixture['HomeTeam'][i] in list(rating['Team']) and fixture['AwayTeam'][i] in list(rating['Team']):
            result = result_percentage(rating, fixture['HomeTeam'][i], fixture['AwayTeam'][i])
            fixture.loc[i, 'Predict'] = decision(result)

    fixture.loc[:, 'Result'] = (fixture.loc[:, 'FTR'] == fixture.loc[:, 'Predict']) * 1

In [252]:
for i in range(len(fixture)):
    predict(fixture[i], table[i])

In [253]:
epl_detail_1819.dropna()

           HomeTeam         AwayTeam FTR Predict  Result
0    Manchester Utd   Leicester City   H       H       1
3      Huddersfield          Chelsea   A       A       1
4     Newcastle Utd        Tottenham   A       A       1
5           Watford  Brighton & Hove   H       H       1
7           Arsenal  Manchester City   A       A       1
8         Liverpool     West Ham Utd   H       H       1
9       Southampton          Burnley   D       A       0
11          Chelsea          Arsenal   H       H       1
12          Everton      Southampton   H       H       1
15     West Ham Utd      Bournemouth   A       H       0
16  Brighton & Hove   Manchester Utd   H       A       0
17          Burnley          Watford   A       H       0
18  Manchester City     Huddersfield   H       H       1
19   Crystal Palace        Liverpool   A       A       1
20          Arsenal     West Ham Utd   H       H       1
21      Bournemouth          Everton   D       H       0
23        Liverpool  Brighton & Hove   H       H       1
24      Southampton   Leicester City   A       A       1
27    Newcastle Utd          Chelsea   A       A       1
28          Watford   Crystal Palace   H       H       1
29   Manchester Utd        Tottenham   A       H       0
31          Chelsea      Bournemouth   H       H       1
32   Crystal Palace      Southampton   A       H       0
33          Everton     Huddersfield   D       H       0
34   Leicester City        Liverpool   A       A       1
35  Manchester City    Newcastle Utd   H       H       1
37          Burnley   Manchester Utd   A       A       1
39          Watford        Tottenham   H       A       0
40      Bournemouth   Leicester City   H       A       0
42     Huddersfield   Crystal Palace   A       A       1
44    Newcastle Utd          Arsenal   A       H       0
45        Tottenham        Liverpool   A       H       0
46          Watford   Manchester Utd   A       A       1
47          Everton     West Ham Utd   A       H       0
49      Southampton  Brighton & Hove   D       H       0
50  Brighton & Hove        Tottenham   A       A       1
51          Burnley      Bournemouth   H       H       1
53   Crystal Palace    Newcastle Utd   D       H       0
55   Leicester City     Huddersfield   H       H       1
56        Liverpool      Southampton   H       H       1
58          Arsenal          Everton   H       H       1
59     West Ham Utd          Chelsea   D       A       0
60          Arsenal          Watford   H       H       1
61          Chelsea        Liverpool   D       H       0
63     Huddersfield        Tottenham   A       A       1
64  Manchester City  Brighton & Hove   H       H       1
65    Newcastle Utd   Leicester City   A       H       0
66     West Ham Utd   Manchester Utd   H       A       0
69      Bournemouth   Crystal Palace   H       H       1

In [254]:
print(epl_detail_1415['Result'].mean())
print(epl_detail_1516['Result'].mean())
print(epl_detail_1617['Result'].mean())
print(epl_detail_1718['Result'].mean())
print(epl_detail_1819['Result'].mean())

(epl_detail_1819['Result'].mean() + epl_detail_1415['Result'].mean() + 
 epl_detail_1516['Result'].mean() + epl_detail_1617['Result'].mean() + (epl_detail_1718['Result'].mean())) / 5

0.35789473684210527
0.3131578947368421
0.3763157894736842
0.36578947368421055
0.42857142857142855

0.36834586466165414